#!/bin/sh
set -e

case "$1" in
    remove|purge)
        glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
        gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
        ;;
esac

#DEBHELPER#
